### ISSUE TITLE
Cursor focus lost when switching windows (linux)

### ISSUE THREAD

**Issue by seinbinder** [JoelEinbinder/snail#31]
When moving from Snail window to another app, snail cursor disappears as expected, but does not reappear when clicking back into snail window. At that point, 'return' is not accepted. Typing a command and 'return' does bring the window focus down to the cursor.
snail-linux-x64.0.11.2

**Comment by JoelEinbinder** [comment]
Fixed via 97df17c10f3fc9438ffae1640f2161a6ca693d72
